packages:
  - "."

allowBuilds:
  "@parcel/watcher": set this to true or false
  esbuild: set this to true or false
  unrs-resolver: set this to true or false
  vue-demi: set this to true or false

patchedDependencies:
  "@mekari/pixel3-nuxt@0.1.2": patches/@mekari__pixel3-nuxt@0.1.2.patch
  "@mekari/pixel3-postcss@1.0.12": patches/@mekari__pixel3-postcss@1.0.12.patch
